version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    assignees:
      - "jpotts244"
    reviewers:
      - "artsy/transact-devs"
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "daily"
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    assignees:
      - "jpotts244"
    reviewers:
      - "artsy/transact-devs"
