---
version: '2'
services:
  aprd:
    command: ["mix", "test"]
    extends:
      file: build.yml
      service: aprd
    environment:
    - MIX_ENV=test
    - DATABASE_HOST=aprd-db
    - DATABASE_USER=postgres
    - RABBITMQ_HOST=aprd-rabbitmq
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWORD=guest
    - RABBITMQ_PORT=5672
    depends_on:
      - aprd-db
  aprd-db:
    image: postgres:9.6-alpine
  aprd-rabbitmq:
    image: rabbitmq:3.6-management-alpine